server: 
  port: 3344 
  
spring:
  application:
    name:  micro-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liucaiming/micro-server-v3-configCenter.git #GitHub上面的git仓库名字
 

